server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示 不 将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/,http://localhost:6002/eureka/